### ISSUE TITLE
Silent update to FreeFileSync reverting to GTK2

### ISSUE THREAD

**Issue by krispya** [flathub/org.freefilesync.FreeFileSync#103]
Hello, I wanted to make you aware that there was a silent update to FreeFileSync reverting from GTK3 to GTK2: https://freefilesync.org/forum/viewtopic.php?t=10103#p37642

Hopefully this can get reflected in the Flatpak version soon. :)

**Comment by kparal** [comment]
Sigh, the upstream developer just loves silent updates. Thanks for notifying me. Can you confirm whether KDE users are affected even when they install from Flathub?

**Comment by krispya** [comment]
The Flathub GTK3 version would freeze on my Steam Deck which I believe uses KDE. I'm new to Linux. But, the silent update reverting to GTK2 works.

**Comment by kparal** [comment]
Sigh, OK, I'll try to publish an update soon.
