### ISSUE TITLE
Looking for a co-maintainer

### ISSUE THREAD

**Issue by kparal** [flathub/org.freefilesync.FreeFileSync#11]
Hello, I'd very appreciate having a co-maintainer for this project. That means:
a) adjusting the patches and building a new FreeFileSync version when the upstream releases one
b) testing at least basic functionality of the new version, to make sure we release something that works

If you're interested in helping out, please reply here. Thanks a lot.

**Comment by GhostPirateBob** [comment]
G'day Kamil, 

I don't have much rep on GitHub, I've got most of my [personal stuff on GitLab](https://gitlab.com/GhostPirateBob) or private right now, and I've just had a month off. 

Anyways, I wrote a more detailed message before realising there is no private message any more. If you are still looking feel free to hit me up at gpiratebob[at_symbol]gmail[dot]com and I'll send you a bit more info.

Have a good one!

**Comment by kparal** [comment]
Hello Pirate Bob, welcome aboard! The release process got much simpler lately, because I switched from compiling FFS from source to re-using pre-built binaries (see a336bc48fa) [1]. So if you are willing to help out, I suggest this:
1. Use RSS to get notified about new FFS releases:
https://freefilesync.org/news-feed.php
2. When a new release is out, update the repo files, built it, run it locally, and test whether it works.
3. Submit a PR here.

I'd really appreciate your help. If this process works fine, I'll grant you the commit access to this repo in some time. Sounds good?

[1] If you wanted to go back to source compilation, I have no problems with that, but I wouldn't be able to help. My hair is now much grayer from all the nonsense one has to fight with in this project and I don't want to repeat the experience.

**Comment by kparal** [comment]
@GhostPirateBob New FreeFileSync 10.18 has just been released. Are you interested in sending a PR to update to the latest version? If you encounter any issues, I'll try to help, just write here, thanks.

**Comment by kparal** [comment]
It seems we've lost a pirate. Version 10.18 has been pushed in #24. Any help with releasing a new version is still welcome. It's much easier now to update the manifest due to using binary sources. But it would still be very helpful if somebody actually tested the new version before we release it publicly.

**Comment by Garbulix** [comment]
Are you looking for someone with a lot of experience or you can also be a some kind mentor? I'm not saying that I am complete useless at the moment. I'm just not that familiar with building in terminal, but I think I could learn that, even myself (but it still would be possible I will need some help and advices).
Also - do you have some fancy testing procedures? I am using FFS only for mirror backup to my another local drive and I am not sure testing if that works could be enough.

**Comment by Garbulix** [comment]
If you are brave enough, you can hold up with building new version of FFS to give me a chance to do it by myself.

**Comment by kparal** [comment]
Hey @Garbulix! Thanks for volunteering! No, no real experience, no fancy procedures required. I'm simply looking for someone to spend the 30 minutes of building and testing a new version instead of me :-) The whole process is described in the readme:
https://github.com/flathub/org.freefilesync.FreeFileSync/blob/master/README.md#maintaining-this-repository
I'll still need to upload the new FFS archives to my mirror (because FFS developer stores them on dubious file hosting sites which can't be linked to directly), but the rest of the process can be easily done by someone else and submitted as a pull request. I can help you with the steps, if something doesn't work for you.
As for testing, I myself do just a simple test of syncing one directory with another. Of course more thorough testing is always welcome.

Let me ping you here when a new FFS release is available, and you can try it?

**Comment by Garbulix** [comment]
Great you've made the guide.
I will monitor FFS news feed and I will write here when I notice about new release. I will also tell you then when I would be able to build the thing.

**Comment by Garbulix** [comment]
I predict new version will be released this week. In that case I would be able to build it next weekend.

**Comment by Garbulix** [comment]
I see there is a new version, please give me couple of days - I want to try build it on my own and test it :)

**Comment by kparal** [comment]
Awesome, thanks @Garbulix. I'll be waiting for a PR.

**Comment by Garbulix** [comment]
I see there is new version. I will try to try it out tomorrow or this weekend and I will make the PR then or write here.

**Comment by Garbulix** [comment]
I see there is new version. I would try it tomorrow I hope. This time I will try more to do it better.

**Comment by Garbulix** [comment]
There is a new version - I can try it on Tuesday at the earliest.

**Comment by Garbulix** [comment]
There is a new version - I'll test soon.

**Comment by Garbulix** [comment]
Maybe close the issue for now? :D 
I would inform you *somehow* if I'd liked to finish my help.

**Comment by kparal** [comment]
Alright :-) Thanks for all your past and future work, @Garbulix, very appreciated!

For anyone also reading this - I am (we are) **always** interested in seeing more helping hands! If you feel like you'd like to participate - please do. Create a PR with a new version, if it isn't available already, report problems (with packaging, not FFS itself), watch this project and help with existing bug reports or PRs, etc. Thanks!
