### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by zWhdmB5T** [flathub/org.freefilesync.FreeFileSync#129]
Thank you!

Thank you for your project and software!

Thank you for maintenance in the past and in the future!

Kind regards and season's greetings!

**Comment by kparal** [comment]
I just maintain the Flahub package. You probably want to thank the original author :-) See here: https://freefilesync.org

**Comment by zWhdmB5T** [comment]
Also for maintaining. It's also a job that has to be done… :-)
