### ISSUE TITLE
Icons are really large

### ISSUE THREAD

**Issue by axredneck** [flathub/org.freefilesync.FreeFileSync#20]
FreeFileSync from Flathub:
![2019-08-19-003957_1920x1080_scrot](https://user-images.githubusercontent.com/20617900/63230819-c1ed3f80-c21a-11e9-8047-0b4304f7d9e3.png)
FreeFileSync from AUR on the same system:
![2019-08-19-004335_1920x1080_scrot](https://user-images.githubusercontent.com/20617900/63230823-cd406b00-c21a-11e9-81f3-bf5686bedac1.png)

**Comment by kparal** [comment]
The size of the icons is actually somehow dependent on the hardware/display you run it on. The icons are much smaller on my desktop than on my laptop (even when using an external monitor). It's somehow scaling the icons depending on the DPI of the primary display or something like that. The 10.15 version changelog contains:
```
Shrink standard system icons if needed (Linux) 
```
so when I get to building it (patches welcome), perhaps this will improve. If not, if somebody can figure out how to configure/fix this in the Flatpak environment, I'll be happy to include the fix.

**Comment by kparal** [comment]
I just pushed version 10.15. Is it better?

**Comment by axredneck** [comment]
No, it isn't. (And now AUR version is affected with the bug too)

**Comment by kparal** [comment]
>  (And now version 10.15 from AUR, unlike 10.14, is affected with the bug too, so it's something wrong with FreeFileSync itself.)

OK, in that case I suggest to report the problem to FFS maintainer (and ideally link it here).

**Comment by axredneck** [comment]
I compiled FreeFileSync from sources and it works well. Does your flatpak use prebuilt Linux binary or is it built from sources?

**Comment by kparal** [comment]
It is built from source. Look at the manifest:
https://github.com/flathub/org.freefilesync.FreeFileSync/blob/master/org.freefilesync.FreeFileSync.yml

**Comment by bgstack15** [comment]
This might be related to a [discussion](https://freefilesync.org/forum/viewtopic.php?t=6114) on the FreeFileSync forum.

**Comment by axredneck** [comment]
Looks more like [this bug report](https://freefilesync.org/forum/viewtopic.php?t=6084)

**Comment by kparal** [comment]
From https://freefilesync.org/forum/viewtopic.php?t=6114#p21790 :
> I'm not sure if someone is actually using the wxWidgets/GTK2 FFS build on a high DPI monitor successfully currently, so I'll disable high DPI support for the next release. At least this build will be usable on all Linux devices until FFS is ready to migrate to GTK3.

So we'll see in the next version.

**Comment by kparal** [comment]
Has the latest 10.17 release fixed this issue? I now take over the prebuilt binaries, instead of building it from source.
