### ISSUE TITLE
No sounds notifications

### ISSUE THREAD

**Issue by kakosf** [flathub/org.freefilesync.FreeFileSync#27]
I have recently installed FreeFileSync (latest version) as a flatpak on Fedora 31 and noticed that there are no working notification sounds at all. 

The error message is:
Couldn't open audio: ALSA: Couldn't open audio device: Connection refused

You can reproduce that by simply doing the following:
Go to Tools > Options > Play a notification sound.

Thanks,
Kyriakos

**Comment by kparal** [comment]
Thanks for the bug report. It should be fixed now and available as an update in an hour or so.
