### ISSUE TITLE
Sync Tasks with Settings..

### ISSUE THREAD

**Issue by cempayzin** [flathub/org.freefilesync.FreeFileSync#33]
Hi,

I think it will be great to create task system to setup the sync operation and run when needed. (In the future we may think about automating it.)

Also, I wanted to create a filter for an absolute directory/file so it will be ignored regardless of the search folders. As far as I see you only have relative filters.

Also, I can help you on testing and adding new features, I have worked on Telecom systems with many many years of experience on real time solutions.

Let me know...

**Comment by kparal** [comment]
I'm sorry, I don't understand what you're talking about. Did you mean to contact the [FFS upstream](https://freefilesync.org/) instead, to develop new features? Because this repo is just about packaging for [Flathub](https://flathub.org/home). I'm not the FFS author.

**Comment by kparal** [comment]
As usual, no response.
