### ISSUE TITLE
No notifications sounds

### ISSUE THREAD

**Issue by kakosf** [flathub/org.freefilesync.FreeFileSync#43]
In previous versions worked as it should be.
In current version 11.2 there no sounds at all, either for comparison or synchronization.
I am on Fedora 33.

**Comment by kparal** [comment]
This is how my Tools->Options looks like:
![options](https://user-images.githubusercontent.com/755451/98247475-f4946c80-1f73-11eb-93c5-30b5974b8d9e.png)

I can play the notification sound just fine using the play button.

Try to run FFS from the terminal:
```
flatpak run org.freefilesync.FreeFileSync
```
and see if there's any error message.

Also download the official FFS version from the homepage and see if you have the same problem in there:
https://freefilesync.org/download.php

**Comment by kparal** [comment]
I'm also on Fedora 33, by the way.

**Comment by kakosf** [comment]
@kparal 
Running FFS from terminal I got the following error msgs:
`Gtk-Message: 16:02:18.522: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:02:18.522: Failed to load module "pk-gtk-module"
`
Still no sounds using the play button.
Additionally, I've tested the latest edition from their website and still no sounds.

**Comment by kparal** [comment]
> Gtk-Message: 16:02:18.522: Failed to load module "canberra-gtk-module"
> Gtk-Message: 16:02:18.522: Failed to load module "pk-gtk-module"

This doesn't seem related.

>  Additionally, I've tested the latest edition from their website and still no sounds.

OK, in that case it's not a problem with Flatpak. Please contact the FFS developer about your problem.
