### ISSUE TITLE
"The GNOME 40 runtime is no longer supported"

### ISSUE THREAD

**Issue by rezad1393** [flathub/org.freefilesync.FreeFileSync#72]
Info: org.gnome.Platform//40 is end-of-life, with reason:
   The GNOME 40 runtime is no longer supported as of March 21, 2022. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   org.freefilesync.FreeFileSync

**Comment by kparal** [comment]
Thank you for your notification. I'll try to update the platform.
